# Generated by Django 4.2.7 on 2023-11-22 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentrequest', '0006_rename_are_you_parent_guardian_studentrequest_are_you_parent_or_guardian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='store_images')),
                ('description', models.CharField(max_length=2000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentrequest.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.revisionbook')),
            ],
        ),
    ]
