# Generated by Django 4.2.7 on 2023-11-18 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentrequest', '0002_remove_studentrequest_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_level', to='studentrequest.yearlevel'),
        ),
    ]
