# Generated by Django 4.2.7 on 2023-11-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentrequest', '0005_alter_studentrequest_parent_guardian_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequest',
            old_name='are you parent/guardian',
            new_name='are_you_parent_or_guardian',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='online only',
            new_name='online_only',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='parent/guardian email',
            new_name='parent_or_guardian_email',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='parent/guardian name',
            new_name='parent_or_guardian_name',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='phone number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='student name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='students email',
            new_name='students_email',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='subject 1',
            new_name='subject1',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='subject 2 (optional)',
            new_name='subject2_optional',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='subject 3 (optional)',
            new_name='subject3_optional',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='subject 4 (optional)',
            new_name='subject4_optional',
        ),
        migrations.RenameField(
            model_name='studentrequest',
            old_name='year level',
            new_name='year_level',
        ),
    ]
