# Generated by Django 4.2.7 on 2023-11-16 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'subjects',
                'ordering': ('subject',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('body_paragraph', models.CharField(max_length=3000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.subject')),
            ],
        ),
    ]
