# Generated by Django 4.2.7 on 2023-11-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentrequest', '0001_initial'),
        ('blog', '0003_subject_backgroundcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='studentrequest.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
